services:
  - type: web
    name: rentease
    runtime: docker
    plan: free
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rentease-db
          property: connectionString
      - key: DJANGO_SERVE_MEDIA
        value: "True"

databases:
  - name: rentease-db
    plan: free
