# Generated by Django 5.1.4 on 2026-05-12 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_cart_rows(apps, schema_editor):
    Cart = apps.get_model('core', 'Cart')
    CartItem = apps.get_model('core', 'CartItem')

    for cart in Cart.objects.all().order_by('user_id', 'id'):
        product_id = getattr(cart, 'product_id', None)
        quantity = getattr(cart, 'quantity', 1) or 1
        if product_id:
            item, created = CartItem.objects.get_or_create(
                cart_id=cart.id,
                product_id=product_id,
                defaults={'quantity': quantity},
            )
            if not created:
                item.quantity = max(item.quantity, quantity)
                item.save(update_fields=['quantity'])

    for user_id in Cart.objects.values_list('user_id', flat=True).distinct():
        user_carts = list(Cart.objects.filter(user_id=user_id).order_by('id'))
        if len(user_carts) < 2:
            continue

        keeper = user_carts[0]
        for duplicate in user_carts[1:]:
            for item in CartItem.objects.filter(cart_id=duplicate.id):
                target, created = CartItem.objects.get_or_create(
                    cart_id=keeper.id,
                    product_id=item.product_id,
                    defaults={'quantity': item.quantity},
                )
                if not created:
                    target.quantity += item.quantity
                    target.save(update_fields=['quantity'])
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_cart_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='monthly_subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash_on_delivery', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='refundable_deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Refurbished', 'Refurbished')], default='Good', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, default='3-5 days', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Active', 'Active'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product'),
        ),
    ]
